### ISSUE TITLE
[REQUEST] add award count on random-meme endpoint

### ISSUE THREAD

**Issue by settlelol** [KSoft-Si/issues#2]
**Is your feature request related to a problem? Please describe.**
no it is not

**Describe the solution you'd like**
can you please add the award count to the random-meme endpoint

**Describe alternatives you've considered**

**Additional context**

**Comment by ember-ana** [comment]
Hi,
I've gone ahead and forwarded this suggestion to the team, as it seems available in the API.

Next time, please take your time to fully fill out the template :)

**Comment by settlelol** [comment]
thank you :) and yea sorry...

**Comment by AndyTempel** [comment]
This feature has been implemented. Docs are being updated. Please note that it might take a few hours to show new features.

Side note: it's under the "awards" field and it's an integer.
