### ISSUE TITLE
[BUG] Lyrics API returns 0 epoch date in some cases

### ISSUE THREAD

**Issue by fixator10** [KSoft-Si/issues#4]
**Describe the bug**
Lyrics API returns `"album_year": "1970"` for songs that definitely released not in 1970.

**To Reproduce**
1. Make request to `/lyrics/search` with next query params: `q=disappearance of hatsune miku` & `limit=3`
2. Check second song, it contains `"album_year": "1970",` field. 
Original version of that remix is released on 08.11.2007, reference: https://vocadb.net/S/295872

**Expected behavior**
Response without `album_year` field, or with proper data

**Client (please complete the following information):**
 - OS: Windows-10-10.0.19041-SP0
 - Client package name: PostmanRuntime/7.26.5
 - Version: N/A (Using V1 token)

**User information:**
 - Your Discord ID: 131813999326134272
 - Your app's Client ID: 257789498153238528

**Comment by AndyTempel** [comment]
This is intentional because sometimes we're unable to find the exact date.

**Comment by fixator10** [comment]
Why its `"1970"` and not `nil`/`"0"`/`""`/missing field then?

Why zero-epoch year? Thats doesnt make any sense and confusing.

**Comment by madebylydia** [comment]
I totally agree, 1970 is confusing, there should be something that clearly indicate it was unable to find, there's no even need to add this value when questionning the API.
