### ISSUE TITLE
[REQUEST] Add support for reddit.com/domain

### ISSUE THREAD

**Issue by cosmicle0** [KSoft-Si/issues#5]
Please add support for `reddit.com/domain`, it's like sub-reddits, but for domains. Here's an example of a reddit.com/domain: [`https://reddit.com/domain/heckifiknowcomics.com`](https://reddit.com/domain/heckifiknowcomics.com).

Thanks,
[CosmicIceDev](https://github.com/CosmicIceDev) :)

**Comment by AndyTempel** [comment]
Please leave interest by liking this comment.
